✅ Started W&B orchestrator run: orchestrator_20250620_221544
✅ Set MLflow experiment to: 'MLOps-Group-Project-Experiment'
▶️  Running step: 'data_load'...
2025/06/20 22:15:47 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 22:15:47 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpi68im9q2 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 22:15:47 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/data_load/run.py' in run with ID 'b4e28c8602ce40acbb0fe77e36108105' ===
2025/06/20 22:16:14 INFO mlflow.projects: === Run (ID 'b4e28c8602ce40acbb0fe77e36108105') succeeded ===
✅ Step 'data_load' finished.
▶️  Running step: 'data_validation'...
2025/06/20 22:16:15 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 22:16:15 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpq9fdl3v_ for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 22:16:15 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/data_validation/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/raw/raw_data.csv'' in run with ID '55b0ecda1e254bcc831f95edbc020f47' ===
2025/06/20 22:16:21 INFO mlflow.projects: === Run (ID '55b0ecda1e254bcc831f95edbc020f47') succeeded ===
✅ Step 'data_validation' finished.
▶️  Running step: 'features'...
2025/06/20 22:16:22 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 22:16:22 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpx58747_7 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 22:16:22 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/features/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/./data/processed/futures_data_processed_.csv'' in run with ID '59839fae924045e081acd8d81e866f4b' ===
2025/06/20 22:16:29 INFO mlflow.projects: === Run (ID '59839fae924045e081acd8d81e866f4b') succeeded ===
✅ Step 'features' finished.
▶️  Running step: 'preprocess'...
2025/06/20 22:16:31 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 22:16:31 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpsn4j1ky3 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 22:16:31 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/preproccess/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/processed/feature_engineered_data.csv'' in run with ID '91c10aa25b6342d6b4d3ef4f592dbc55' ===
2025/06/20 22:16:38 INFO mlflow.projects: === Run (ID '91c10aa25b6342d6b4d3ef4f592dbc55') succeeded ===
✅ Step 'preprocess' finished.
▶️  Running step: 'models'...
2025/06/20 22:16:39 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 22:16:39 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp_nl3aojr for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 22:16:39 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/models/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/processed/training_data'' in run with ID '620d99b4189e4668ac5dd1dd92727bb7' ===
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 141, in main
    mlflow.run(".", entry_point=step, parameters=params)
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 374, in run
    _wait_for(submitted_run_obj)
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 391, in _wait_for
    raise ExecutionException(f"Run (ID '{run_id}') failed")
mlflow.exceptions.ExecutionException: Run (ID '620d99b4189e4668ac5dd1dd92727bb7') failed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
